export type Country = { code: string; name: string; nameJa: string; dial: string; flag: string };

// Japan and India first — the two markets the book ships to — then the rest A→Z.
export const COUNTRIES: Country[] = [
  { code: "JP", name: "Japan", nameJa: "日本", dial: "+81", flag: "🇯🇵" },
  { code: "IN", name: "India", nameJa: "インド", dial: "+91", flag: "🇮🇳" },
  { code: "AE", name: "United Arab Emirates", nameJa: "アラブ首長国連邦", dial: "+971", flag: "🇦🇪" },
  { code: "AR", name: "Argentina", nameJa: "アルゼンチン", dial: "+54", flag: "🇦🇷" },
  { code: "AU", name: "Australia", nameJa: "オーストラリア", dial: "+61", flag: "🇦🇺" },
  { code: "AT", name: "Austria", nameJa: "オーストリア", dial: "+43", flag: "🇦🇹" },
  { code: "BD", name: "Bangladesh", nameJa: "バングラデシュ", dial: "+880", flag: "🇧🇩" },
  { code: "BE", name: "Belgium", nameJa: "ベルギー", dial: "+32", flag: "🇧🇪" },
  { code: "BR", name: "Brazil", nameJa: "ブラジル", dial: "+55", flag: "🇧🇷" },
  { code: "CA", name: "Canada", nameJa: "カナダ", dial: "+1", flag: "🇨🇦" },
  { code: "CH", name: "Switzerland", nameJa: "スイス", dial: "+41", flag: "🇨🇭" },
  { code: "CL", name: "Chile", nameJa: "チリ", dial: "+56", flag: "🇨🇱" },
  { code: "CN", name: "China", nameJa: "中国", dial: "+86", flag: "🇨🇳" },
  { code: "CO", name: "Colombia", nameJa: "コロンビア", dial: "+57", flag: "🇨🇴" },
  { code: "CZ", name: "Czechia", nameJa: "チェコ", dial: "+420", flag: "🇨🇿" },
  { code: "DE", name: "Germany", nameJa: "ドイツ", dial: "+49", flag: "🇩🇪" },
  { code: "DK", name: "Denmark", nameJa: "デンマーク", dial: "+45", flag: "🇩🇰" },
  { code: "EG", name: "Egypt", nameJa: "エジプト", dial: "+20", flag: "🇪🇬" },
  { code: "ES", name: "Spain", nameJa: "スペイン", dial: "+34", flag: "🇪🇸" },
  { code: "FI", name: "Finland", nameJa: "フィンランド", dial: "+358", flag: "🇫🇮" },
  { code: "FR", name: "France", nameJa: "フランス", dial: "+33", flag: "🇫🇷" },
  { code: "GB", name: "United Kingdom", nameJa: "イギリス", dial: "+44", flag: "🇬🇧" },
  { code: "GR", name: "Greece", nameJa: "ギリシャ", dial: "+30", flag: "🇬🇷" },
  { code: "HK", name: "Hong Kong", nameJa: "香港", dial: "+852", flag: "🇭🇰" },
  { code: "ID", name: "Indonesia", nameJa: "インドネシア", dial: "+62", flag: "🇮🇩" },
  { code: "IE", name: "Ireland", nameJa: "アイルランド", dial: "+353", flag: "🇮🇪" },
  { code: "IL", name: "Israel", nameJa: "イスラエル", dial: "+972", flag: "🇮🇱" },
  { code: "IT", name: "Italy", nameJa: "イタリア", dial: "+39", flag: "🇮🇹" },
  { code: "KE", name: "Kenya", nameJa: "ケニア", dial: "+254", flag: "🇰🇪" },
  { code: "KR", name: "South Korea", nameJa: "韓国", dial: "+82", flag: "🇰🇷" },
  { code: "LK", name: "Sri Lanka", nameJa: "スリランカ", dial: "+94", flag: "🇱🇰" },
  { code: "MX", name: "Mexico", nameJa: "メキシコ", dial: "+52", flag: "🇲🇽" },
  { code: "MY", name: "Malaysia", nameJa: "マレーシア", dial: "+60", flag: "🇲🇾" },
  { code: "NG", name: "Nigeria", nameJa: "ナイジェリア", dial: "+234", flag: "🇳🇬" },
  { code: "NL", name: "Netherlands", nameJa: "オランダ", dial: "+31", flag: "🇳🇱" },
  { code: "NO", name: "Norway", nameJa: "ノルウェー", dial: "+47", flag: "🇳🇴" },
  { code: "NP", name: "Nepal", nameJa: "ネパール", dial: "+977", flag: "🇳🇵" },
  { code: "NZ", name: "New Zealand", nameJa: "ニュージーランド", dial: "+64", flag: "🇳🇿" },
  { code: "PH", name: "Philippines", nameJa: "フィリピン", dial: "+63", flag: "🇵🇭" },
  { code: "PK", name: "Pakistan", nameJa: "パキスタン", dial: "+92", flag: "🇵🇰" },
  { code: "PL", name: "Poland", nameJa: "ポーランド", dial: "+48", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", nameJa: "ポルトガル", dial: "+351", flag: "🇵🇹" },
  { code: "QA", name: "Qatar", nameJa: "カタール", dial: "+974", flag: "🇶🇦" },
  { code: "RO", name: "Romania", nameJa: "ルーマニア", dial: "+40", flag: "🇷🇴" },
  { code: "RU", name: "Russia", nameJa: "ロシア", dial: "+7", flag: "🇷🇺" },
  { code: "SA", name: "Saudi Arabia", nameJa: "サウジアラビア", dial: "+966", flag: "🇸🇦" },
  { code: "SE", name: "Sweden", nameJa: "スウェーデン", dial: "+46", flag: "🇸🇪" },
  { code: "SG", name: "Singapore", nameJa: "シンガポール", dial: "+65", flag: "🇸🇬" },
  { code: "TH", name: "Thailand", nameJa: "タイ", dial: "+66", flag: "🇹🇭" },
  { code: "TR", name: "Türkiye", nameJa: "トルコ", dial: "+90", flag: "🇹🇷" },
  { code: "TW", name: "Taiwan", nameJa: "台湾", dial: "+886", flag: "🇹🇼" },
  { code: "UA", name: "Ukraine", nameJa: "ウクライナ", dial: "+380", flag: "🇺🇦" },
  { code: "US", name: "United States", nameJa: "アメリカ合衆国", dial: "+1", flag: "🇺🇸" },
  { code: "VN", name: "Vietnam", nameJa: "ベトナム", dial: "+84", flag: "🇻🇳" },
  { code: "ZA", name: "South Africa", nameJa: "南アフリカ", dial: "+27", flag: "🇿🇦" },
];

export const COUNTRY_CODES = new Set(COUNTRIES.map((c) => c.code));
